export const plans = [
  {
    id: 1,
    name: "Basic",
    localprice: "Free ",
    internationalprice: "10$",
    features: ["1 Campaign/ Month", "Up to 255 users", "Single Domain"],
    btnText: "Select",
    bgColor: "white",
    txColor: "black",
  },
  {
    id: 2,
    name: "Startup",
    localprice: "1,250$ ",
    internationalprice: "10$",
    features: [
      "1 Campaign/ Month",
      "Up to 255 users",
      "Single Domain",
      "Single Domain",
      "Single Domain",
      "Single Domain",
    ],
    btnText: "Select",
    bgColor: "#1A1C29",
    txColor: "white",
  },
  {
    id: 3,
    name: "Enterprise",
    localprice: "2,500$ ",
    internationalprice: "10$",
    features: ["1 Campaign/ Month", "Up to 255 users", "Single Domain"],
    btnText: "Select",
    bgColor: "white",
    txColor: "black",
  },
];
